### PR TITLE
notebook for generating sims values

### PR DESCRIPTION
**Pull request by yoachim**
Add a notebook that generates output that can drop directly into `sims_utils`

### CODE REVIEW

**Comment by rhiannonlynne** [comment]
Normally PRs on syseng_throughputs require two approving reviewers, since this is considered a sensitive repo for system engineering values. 
However, this is just adding a notebook and not touching the throughput curves or python code.

**Review by rhiannonlynne — APPROVED** [review]

**Comment by rhiannonlynne** [comment]
I'm going to approve it and then just tag @bxin for another review. 
Bo - this PR adds a notebook to the repo which reformats some of the values calculated for m5 (Cm/zp/kAtm/ etc.) so that we can paste them easily into a class in sims_utils (https://github.com/lsst/sims_utils/pull/52/files#diff-3bbc4015545d140546fe8c5c1b604dc87b7c0741aa3a70a908f3d7cd93c5e609 - SysEngValues) .. from there, these values are used in lsst.sims.utils.m5_flat_sed.

**Review by bxin — APPROVED** [review]
Looks good to me!
and runs without problem.

**Comment by rhiannonlynne** [comment]
Deleting branch u/yoachim/generate_sims_vals

**Pull request merged**
