### PR TITLE
M2 coating run in July 2019

### PR DESCRIPTION
**Pull request by bxin**
This update includes the M2 reflectivity curve based on witness sample measurements from M2 coating run in July 2019
The M2 curve is getting a bit better than the June 2019 update. 
See the latest m5 values in https://github.com/lsst-pst/syseng_throughputs/blob/update/M2Coating1907/documentation/Confirm%20Updates.ipynb

### CODE REVIEW

**Review by rhiannonlynne — APPROVED** [review]
I am curious though - why is there a difference between the June and July sample? Was the coating method changed?

**Comment by bxin** [comment]
Here is an answer from Tomi - "the reflectivity improvement is basically in the coating process, a better process gas tuning, power, mask shape, rotation speed, etc. All the coating related parameters."

**Comment by rhiannonlynne** [comment]
@ivezic or @cclaver or @sandrinethomas -- can we get the additional final reviewer approval?

**Review by cclaver — APPROVED** [review]
Updated M2 protected Ag reflectivity matches measured values post M2 coating in Chile.

**Comment by rhiannonlynne** [comment]
Deleting branch update/M2Coating1907

**Pull request merged**
